name: Check Python packages
on:
  push:
    branches:
      - main
    paths:
      - packages/python/**
  pull_request:
    paths:
      - packages/python/**

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [openpipeline_testutils]

    steps:
    - uses: actions/checkout@v6

    - name: Using Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"

    - name: Install tox
      run: python -m pip install tox

    - name: Run tox lint
      run: |
        cd packages/python/${{ matrix.package }}
        tox -e lint
